<a href="https://colab.research.google.com/github/Manase2008/ML-Projects/blob/main/Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split, GridSearchCV

from sklearn.tree import export_graphviz, DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
data = pd.read_csv('train.csv')
data = data.dropna(how='any')
categorical_cols = ['PassengerId', 'Ticket', 'Pclass', 'Name', 'Sex', 'Fare', 'Cabin', 'Embarked']

for col in categorical_cols:
    if col in data.columns:
        data[col] = encoder.fit_transform(data[col])

In [ ]:
y = data.Survived
X = data.drop(['PassengerId', 'Survived', 'Name', 'SibSp', 'Ticket', 'Fare'], axis=1)
X

     Pclass  Sex   Age  Parch  Cabin  Embarked
1         0    0  38.0      0     72         0
3         0    0  35.0      0     48         2
6         0    1  54.0      0    117         2
10        2    0   4.0      1    131         2
11        0    0  58.0      0     43         2
..      ...  ...   ...    ...    ...       ...
871       0    0  47.0      1     91         2
872       0    1  33.0      0     29         2
879       0    0  56.0      1     61         0
887       0    0  19.0      0     25         2
889       0    1  26.0      0     52         0

[183 rows x 6 columns]

In [ ]:
X_scaled = scaler.fit_transform(X)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [ ]:
model1 = DecisionTreeClassifier(criterion='entropy', max_depth=2)
model1.fit(X_train, y_train)
prediction1 = model1.predict(X_test)
accuracy_score(prediction1, y_test)

0.8108108108108109

In [ ]:
data = pd.read_csv('adult.data.csv', header=None)
data = data.dropna(how='any')
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
categorical_cols = [1, 3, 5, 6, 7, 8, 9, 13, 14]

for col in categorical_cols:
    if col in data.columns:
        data[col] = encoder.fit_transform(data[col])
data

       0   1       2   3   4   5   6   7   8   9      10  11  12  13  14
0      39   7   77516   9  13   4   1   1   4   1   2174   0  40  39   0
1      50   6   83311   9  13   2   4   0   4   1      0   0  13  39   0
2      38   4  215646  11   9   0   6   1   4   1      0   0  40  39   0
3      53   4  234721   1   7   2   6   0   2   1      0   0  40  39   0
4      28   4  338409   9  13   2  10   5   2   0      0   0  40   5   0
...    ..  ..     ...  ..  ..  ..  ..  ..  ..  ..    ...  ..  ..  ..  ..
32556  27   4  257302   7  12   2  13   5   4   0      0   0  38  39   0
32557  40   4  154374  11   9   2   7   0   4   1      0   0  40  39   1
32558  58   4  151910  11   9   6   1   4   4   0      0   0  40  39   0
32559  22   4  201490  11   9   4   1   3   4   1      0   0  20  39   0
32560  52   5  287927  11   9   2   4   5   4   0  15024   0  40  39   1

[32561 rows x 15 columns]

In [ ]:
X = data.drop([14], axis=1)
y = data[14]
y

0        0
1        0
2        0
3        0
4        0
        ..
32556    0
32557    1
32558    0
32559    0
32560    1
Name: 14, Length: 32561, dtype: int64

In [ ]:
X_scale = scaler.fit_transform(X)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_scale, y, test_size=0.2, random_state=42)

In [ ]:
model1 = DecisionTreeClassifier(criterion='gini', max_depth=7)
model1.fit(X_train, y_train)
prediction1 = model1.predict(X_test)
accuracy_score(prediction1, y_test)

0.8570551205281745

In [ ]:
model2 = DecisionTreeClassifier(criterion='gini', max_depth=7)
model1.fit(X_train, y_train)
prediction1 = model1.predict(X_train)
accuracy_score(prediction1, y_train)

0.859835687960688