<a href="https://colab.research.google.com/github/Manase2008/ML-Projects/blob/main/Prediction_of_military_or_economy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
hey = pd.read_csv('armenpress_army.csv')
hey1 = pd.read_csv('armenpress_economy.csv')
# upload from your computer the files
hey['type'] = 'military'
hey1['type'] = 'economy'

In [ ]:
merged_data = pd.merge(hey, hey1, how = 'outer')
merged_data

,article_title,article_paragraph,type
0,1 out of 58 new confirmed coronavirus cases in...,"YEREVAN, MARCH 30, ARMENPRESS. 1 out of the 58...",military
1,"1 soldier killed, 1 wounded in unknown circums...","YEREVAN, DECEMBER 2, ARMENPRESS. One soldier h...",military
2,200 jobs to be created in arms and ammunition ...,"YEREVAN, FEBRUARY 21, ARMENPRESS. The Armenian...",economy
3,A lot has changed in defense sector in terms o...,"YEREVAN, DECEMBER 9, ARMENPRESS. Deputy defens...",military
4,About three dozen servicemen and war volunteer...,"YEREVAN, JANUARY 28, ARMENPRESS. About three d...",military
...,...,...,...
368,‘We close the year with quite a good mood’ – A...,"YEREVAN, DECEMBER 26, ARMENPRESS. During today...",economy
369,‘We need victory of individual effort: governm...,"DILIJAN, JUNE 22, ARMENPRESS. The Armenian gov...",economy
370,"“If environmental risks are manageable, there ...","YEREVAN, AUGUST 26, ARMENPRESS. The Investigat...",economy
371,“Now that’s a gift” – Armenia receives SU-30SM...,"YEREVAN, DECEMBER 27, ARMENPRESS. The 4 units ...",military
372,"“Shameful chapter of 80’s weapons” is over, Pa...","KAPAN, JANUARY 25, ARMENPRESS. Prime Minister ...",military

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

merged_data["type"] = encoder.fit_transform(merged_data["type"])

In [ ]:
random_merged_data = merged_data.sample(frac=1, random_state=42).reset_index(drop=True)
random_merged_data

,article_title,article_paragraph,type
0,Russian SU-30SM multirole fighter aircrafts to...,"YEREVAN, JULY 22, ARMENPRESS. The Russian SU-3...",1
1,Armenia should become technological country wi...,"YEREVAN, APRIL 22, ARMENPRESS. Prime Minister ...",0
2,"Armenia economic activity grows 8,9% in Januar...","YEREVAN, FEBRUARY 25, ARMENPRESS. Economic act...",0
3,Process manufacturing became leader of growth ...,"YEREVAN, FEBRUARY 21, ARMENPRESS. The 7,6% eco...",0
4,Armenian FM declines to comment on POW situati...,"YEREVAN, AUGUST 14, ARMENPRESS. Armenian FM Zo...",1
...,...,...,...
368,Armenian defense minister hosts US Congress me...,"YEREVAN, OCTOBER 8, ARMENPRESS. Defense Minist...",1
369,Armenian servicemen injured by Azerbaijani fir...,"YEREVAN, APRIL 30, ARMENPRESS. Contractual ser...",1
370,"Nearly ten days later, critically wounded Arts...","YEREVAN, MAY 13, ARMENPRESS. A soldier of the ...",1
371,Strategic military drills in unprecedented sca...,"YEREVAN, SEPTEMBER 19, ARMENPRESS. The Armenia...",1
372,Armenian military “actively” supplementing ars...,"YEREVAN, DECEMBER 6, ARMENPRESS. Armenia has b...",1

In [ ]:
X = random_merged_data.drop('type', axis=1)
y = random_merged_data['type']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(stop_words='english', ngram_range=(1,1) )
X_train_counts = vectorizer.fit_transform(X_train['article_paragraph'])
X_test_counts = vectorizer.transform(X_test['article_paragraph'])

In [ ]:
from sklearn.naive_bayes import MultinomialNB

# Initialize the model
nb_classifier = MultinomialNB()

# Train the model
nb_classifier.fit(X_train_counts, y_train)

MultinomialNB()

In [ ]:
from sklearn.metrics import accuracy_score

# Make predictions
predictions = nb_classifier.predict(X_test_counts)

# Check accuracy
print("Accuracy:", accuracy_score(y_test, predictions))

Accuracy: 0.9821428571428571

In [ ]:
new_data = ['The government of Armenia is seriously keeping track of its water resources', 'There has been signed a serious military contract between USA and Armenia']
new_data_vector = vectorizer.transform(new_data)
predictions = nb_classifier.predict(new_data_vector)
predictions

array([0, 1])