<a href="https://colab.research.google.com/github/Manase2008/ML-Projects/blob/main/Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('california_housing_train.csv')
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
test = pd.read_csv('california_housing_test.csv')
test

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
X = data.drop(['median_house_value'], axis=1)
y = data['median_house_value']
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
X_test = test.drop(['median_house_value'], axis=1)
y_test = test['median_house_value']
X_test_scaled = scaler.fit_transform(X_test)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [ ]:
model = LinearRegression()
model.fit(X_scaled, y)

LinearRegression()

In [ ]:
prediction = model.predict(X_test_scaled)

In [ ]:
# Metrics
r2 = r2_score(y_test, prediction)
mae = mean_absolute_error(y_test, prediction)
mse = mean_squared_error(y_test, prediction)
rmse = np.sqrt(mse)

print('r2 accuracy:', r2)
print('mae accuracy:', mae)
print('mse accuracy:', mse)
print('rmse accuracy:', rmse)

r2 accuracy: 0.6180349003715606
mae accuracy: 50669.44609099072
mse accuracy: 4886020526.855479
rmse accuracy: 69900.07529935485

In [ ]:
prediction

array([358460.00878369, 216569.51471133, 276384.95549539, ...,
        90664.64488211, 151950.61857716, 466849.37460678])

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [ ]:
data = pd.read_excel('synthetic_loan_risk.xlsx')
data

,Age,Income,CreditScore,YearsJob,Debt,House,Savings,Dependents,EducationLevel,LatePayments,LoanAmount,EmploymentType,MaritalStatus,Region,MonthlyExpenses,Default
0,61,39592,512,17,16049,Yes,36579,5,HighSchool,2,82397,Contract,Single,North,1267,No
1,34,55495,758,38,1739,Yes,187700,5,PhD,7,63878,SelfEmployed,Single,South,6219,No
2,48,69597,642,9,14110,No,26793,0,PhD,3,52052,SelfEmployed,Divorced,East,7111,No
3,23,120647,735,34,8180,No,20656,4,Master,11,80674,PartTime,Divorced,North,875,No
4,63,54871,648,5,15256,Yes,99647,2,PhD,11,26319,SelfEmployed,Married,South,5990,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1655,55,70974,557,24,2428,Yes,27726,0,HighSchool,10,75388,FullTime,Single,West,4927,Yes
1656,46,124280,646,38,35118,No,66925,3,PhD,13,21633,PartTime,Married,West,981,Yes
1657,21,90562,769,17,20444,No,67847,0,Bachelor,14,91160,FullTime,Divorced,North,5184,No
1658,23,89316,649,39,37175,Yes,22479,3,Master,1,11599,Contract,Divorced,South,3719,No
1659,59,120730,820,8,12935,No,60414,2,Master,13,40444,Contract,Single,South,1460,No

In [ ]:
categorical_cols = ['EducationLevel', 'House', 'EmploymentType', 'MaritalStatus', 'Region', 'YearsJob']

# Apply LabelEncoder to these columns
for col in categorical_cols:
    if col in data.columns:
        data[col] = encoder.fit_transform(data[col])

In [ ]:
X = data.drop('Default', axis=1)
y = data['Default']

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [ ]:
model = LogisticRegression(max_iter=100000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=100000)

In [ ]:
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8765060240963856

In [ ]:
data = pd.read_csv('california_housing_train.csv')
test = pd.read_csv('california_housing_test.csv')

In [ ]:
X = data.drop(['median_house_value'], axis=1)
y = data['median_house_value']
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
X_test = test.drop(['median_house_value'], axis=1)
y_test = test['median_house_value']
X_test_scaled = scaler.fit_transform(X_test)

In [ ]:
from sklearn.svm import SVR
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

model = SVR(
    kernel="rbf",
    C=1.0,
    epsilon=0.1
)

model.fit(X_scaled, y)

predictions = model.predict(X_test_scaled)
r2 = r2_score(y_test, predictions)
mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
rmse = np.sqrt(mse)

print("R-squared:", r2)
print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)

R-squared: -0.04467357712290165
Mean Absolute Error: 86305.28840602761
Mean Squared Error: 13363253728.289042
Root Mean Squared Error: 115599.5403463571